### ISSUE TITLE
sampler_tonemap.py

### ISSUE THREAD

**Issue by WASasquatch** [comfyanonymous/ComfyUI_experiments#1]
This sounded like a great idea, but when I look at your code, you are not actually tone mapping from a range. You're just normalizing the noise prediction. Shouldn't you be clipping between a range?

**Comment by comfyanonymous** [comment]
It's named "tonemap" because the algorithm is based on the simple reinhard tone mapping algorithm. I just treat the magnitude of the latent vectors as the "luminance".

In the future I might try to implement this but with a local tonemapping algorithm instead to see what the effect is.

**Comment by WASasquatch** [comment]
> I just treat the magnitude of the latent vectors as the "luminance"

Oh! Ok, I see what you're doing. Yeah that makes sense.
