### ISSUE TITLE
Rescale CFG nodes not working.

### ISSUE THREAD

**Issue by rabidcopy** [comfyanonymous/ComfyUI_experiments#12]
Seems with changes to ComfyUI recently, these nodes don't seem to work correctly anymore. Changes below seem to fix it? Albeit it doesn't seem 1:1 to how it worked before. Results look more washed out at typical values around 0.4-0.7 and detail is less sharp.

```
        def rescale_cfg(args):
            input = args["input"]
            cond = input - args["cond"]
            uncond = input - args["uncond"]
            cond_scale = args["cond_scale"]

            x_cfg = uncond + cond_scale * (cond - uncond)
            ro_pos = torch.std(cond, dim=(1,2,3), keepdim=True)
            ro_cfg = torch.std(x_cfg, dim=(1,2,3), keepdim=True)

            x_rescaled = x_cfg * (ro_pos / ro_cfg)
            x_final = multiplier * x_rescaled + (1.0 - multiplier) * x_cfg

            return input - x_final
```

**Comment by ponchojohn1234** [comment]
can confirm, it's closer to it's old behavior, the current code doesn't seem to do much of anything

**Comment by rabidcopy** [comment]
Fixed by https://github.com/comfyanonymous/ComfyUI/commit/58d5d71a93908c6edd783d85557c2556b2e179c7.
https://github.com/comfyanonymous/ComfyUI/issues/1923#issuecomment-1806624946
