### ISSUE TITLE
Reference Only might be the missing Key to transfer animation but can't handle animation 

### ISSUE THREAD

**Issue by if-ai** [comfyanonymous/ComfyUI_experiments#13]
Reference only node is good but it would be great if it could handle animation. I am making a workflow to transfer old animations onto new characters. 
I tried IP adapter but the result is nowhere as good as the reference only or in combination. If it only worked with animation the result would be more consistent.

I am here to ask you to please consider designing the code to work with animation. It will improve a lot the consistency even if is not perfect, it would save tons of time as there will be less inconsistent animation to fix.

The current behavior I encounter seems to be that it takes the batch size field on the ROS node and process the first and second frames of the source animation s and the latent given from the VAE encode of the reference image. Then repeats as many frames in the animation 

![thorium_aTgPBmKRWn](https://github.com/comfyanonymous/ComfyUI_experiments/assets/21185218/2595268e-9077-49e4-a8d6-c1b7e0428f2c)

[workflow (77).json](https://github.com/comfyanonymous/ComfyUI_experiments/files/13487119/workflow.77.json)

**Comment by if-ai** [comment]
https://github.com/comfyanonymous/ComfyUI_experiments/assets/21185218/f926a7fb-3f50-4c82-bf6a-6f2b955ec0a4

**Comment by if-ai** [comment]
I made a mistake it looks like it works with animation as is by selecting a batch index other than 0

**Comment by Affegithub** [comment]
hi, I think I am having same issue with you rn, but it doesn't clear although I changed a batch index. If possible, could you share me the workflow that you could solve the issue?
