### ISSUE TITLE
feat: sd-dynamic-thresholding-rcfg

### ISSUE THREAD

**Issue by jjangga0214** [comfyanonymous/ComfyUI_experiments#3]
Hi!
In A1111 web ui, I am using sd-dynamic-thresholding-rcfg, not sd-dynamic-thresholding, and found it useful.
https://github.com/ashen-sensored/sd-dynamic-thresholding-rcfg
I wish I can use it in ComfyUI.
How do you think?
Thanks :)

**Comment by comfyanonymous** [comment]
See this repo: https://github.com/comfyanonymous/ComfyUI_experiments

**Comment by jjangga0214** [comment]
Thank you very much. I am going to experiment on it.

**Comment by jjangga0214** [comment]
@comfyanonymous Hi! I've taken it and had experimentation.
Currently, it has a single option, multiplier.
But [ashen-sensored/sd-dynamic-thresholding-rcfg](https://github.com/ashen-sensored/sd-dynamic-thresholding-rcfg) has practical options. 
For example, just to say one, the [scheduler](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/wiki/Schedulers) matters as well.

<img width="1065" alt="스크린샷 2023-06-26 오후 11 41 52" src="https://github.com/comfyanonymous/ComfyUI_experiments/assets/28584151/6b1a50aa-22da-48ae-999c-94c5cb2af680">

I fully understand this node is experiments.
But what I found is that sd-dynamic-thresholding-rcfg helps to fix Stable Diffusion's algorithm mistake, which means it's a very critical feature.

So I want to ask if you have any other thoughts on dynamic thresholding rcfg.

Thanks :)
